"""
app/content/adapters/pptx_adapter.py

PPTX presentation extraction, search, and generation adapter for AURA using python-pptx.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pptx
from pptx.util import Inches, Pt

from app.content.adapters.base import BaseContentAdapter
from app.content.models import (
    BlockType,
    ContentBlock,
    ContentDocument,
    ContentSection,
    ContentType,
)


class PPTXAdapter(BaseContentAdapter):
    """Extracts, indexes, searches, and generates PowerPoint (.pptx) presentations."""

    def extract(self, source_path_or_url: str) -> ContentDocument:
        """Extract slides, titles, text blocks, and notes from a PPTX file."""
        path = Path(source_path_or_url).resolve()
        if not path.exists():
            raise FileNotFoundError(f"PPTX file not found: '{path}'")

        try:
            prs = pptx.Presentation(str(path))
        except Exception as e:
            raise RuntimeError(f"Failed to open PPTX '{path}': {e}")

        sections: list[ContentSection] = []

        for idx, slide in enumerate(prs.slides, start=1):
            slide_title = ""
            blocks: list[ContentBlock] = []

            for shape in slide.shapes:
                if shape.has_text_frame:
                    text = shape.text_frame.text.strip()
                    if not text:
                        continue

                    if shape == slide.shapes.title or not slide_title:
                        slide_title = text.split("\n")[0]
                        blocks.append(ContentBlock(block_type=BlockType.HEADING, text=text))
                    else:
                        blocks.append(ContentBlock(block_type=BlockType.PARAGRAPH, text=text))

            # Extract speaker notes if available
            notes_text = ""
            if slide.has_notes_slide and slide.notes_slide.notes_text_frame:
                notes_text = slide.notes_slide.notes_text_frame.text.strip()
                if notes_text:
                    blocks.append(
                        ContentBlock(
                            block_type=BlockType.PARAGRAPH,
                            text=f"Notes: {notes_text}",
                            metadata={"is_speaker_notes": True},
                        )
                    )

            sections.append(
                ContentSection(
                    title=slide_title or f"Slide {idx}",
                    location=f"Slide {idx}",
                    blocks=blocks,
                    raw_text="\n".join(b.text for b in blocks),
                    metadata={"slide_number": idx, "has_notes": bool(notes_text)},
                )
            )

        return ContentDocument(
            title=path.stem,
            source_type=ContentType.PPTX,
            source_path=str(path),
            sections=sections,
            slide_count=len(prs.slides),
            metadata={"slide_count": len(prs.slides)},
        )

    def create_presentation(
        self,
        output_path: str | Path,
        title: str = "Presentation",
        subtitle: str = "Generated by AURA",
        slides: list[dict[str, Any]] | None = None,
    ) -> str:
        """Create a new PowerPoint presentation file."""
        target = Path(output_path).resolve()
        target.parent.mkdir(parents=True, exist_ok=True)

        prs = pptx.Presentation()

        # Slide 1: Title slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = title
        if len(slide.placeholders) > 1 and subtitle:
            slide.placeholders[1].text = subtitle

        # Content slides
        bullet_slide_layout = prs.slide_layouts[1]
        for item in (slides or []):
            s_title = item.get("title") or "Summary"
            s_bullets = item.get("bullets") or ([item["content"]] if "content" in item else [])

            c_slide = prs.slides.add_slide(bullet_slide_layout)
            c_slide.shapes.title.text = s_title
            tf = c_slide.placeholders[1].text_frame

            for b_idx, bullet in enumerate(s_bullets):
                if b_idx == 0:
                    tf.text = str(bullet)
                else:
                    p = tf.add_paragraph()
                    p.text = str(bullet)

        prs.save(str(target))
        return str(target)
